---
# FIXME: hostvars isn't flexible. This should be passed in to simplify
- name: Join as a manager
  # docker swarm join --token MANAGER_TOKEN HOST:PORT
  shell: "docker swarm join --token {{ hostvars['node-1']['manager_token']['stdout'] }} {{ hostvars['node-1']['ansible_enp0s8']['ipv4']['address'] }}:2377"
  when: docker_info.stdout.find("Swarm{{':'}} inactive") != -1
  retries: 3
  delay: 20
