---
# FIXME: hostvars isn't flexible. This should be passed in to simplify
- name: Join as a worker
  # docker swarm join --token WORKER_TOKEN HOST:PORT
  shell: "docker swarm join --token {{ hostvars['node-1']['worker_token']['stdout'] }} {{ hostvars['node-1']['ansible_enp0s8']['ipv4']['address'] }}:2377"
  when: "docker_info.stdout.find('Swarm: inactive') != -1"
  retries: 3
  delay: 20
